workout_journal_dbt:
  outputs:
    dev:
      dbname: "{{ env_var('WORKOUT_DB_NAME') }}"
      host: localhost
      pass: "{{ env_var('WORKOUT_DB_PASSWORD') }}"
      port: 5432
      schema: intermediate
      threads: 1
      type: postgres
      user: "{{ env_var('WORKOUT_DB_USER') }}"

    dev-docker:
      dbname: "{{ env_var('WORKOUT_DB_NAME') }}"
      host: host.docker.internal
      pass: "{{ env_var('WORKOUT_DB_PASSWORD') }}"
      port: 5432
      schema: intermediate
      threads: 1
      type: postgres
      user: "{{ env_var('WORKOUT_DB_USER') }}"

    prod:
      dbname: "{{ env_var('WORKOUT_DB_NAME') }}"
      host: "{{ env_var('WORKOUT_DB_HOST') }}"
      pass: "{{ env_var('WORKOUT_DB_PASSWORD') }}"
      port: 5432
      schema: intermediate
      threads: 1
      type: postgres
      user: "{{ env_var('WORKOUT_DB_USER') }}"

  target: "{{ env_var('DBT_TARGET', 'dev') }}"  # defaults to 'dev' if not set
